server:
  port: 8081
  servlet:
    context-path: /shop
    multipart:
      max-file-size: 10MB  
      max-request-size: 100MB

spring:
     datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3307/db_shopmaster?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
#        url: jdbc:mysql://localhost:3307/db_shopmaster?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
        username: root
        password: 1234
     jpa:
       show-sql: true
     mvc:
       view:
         prefix: /WEB-INF/views/
         suffix: .jsp


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.ssmschoolshop.entity

devtools:
    restart:
      enabled: true 
pagehelper:
  pagehelperDialect: mysql
  reasonable: true
  support-methods-arguments: true


logging:
    level:
       com.zhang.ssmschoolshop.dao: DEBUG









